" Basic Configuration
set nocompatible
syntax on
filetype plugin indent on

" UI and Usability
set number
set ruler
set showcmd
set showmatch
set cursorline
set title
set notitle
set ls=2
set mouse=a
set visualbell t_vb=
set t_vb=
set timeout timeoutlen=3000 ttimeoutlen=100
set hidden
set history=200
set wildmenu
set wildmode=longest:full
set background=dark
set cc=81

" Backspace behavior
set backspace=indent,eol,start
set bs=2

" Tabs and Indentation
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set expandtab
set ai

" Makefile sanity
autocmd BufEnter ?akefile* set noet ts=8 sw=8
autocmd BufEnter */debian/rules set noet ts=8 sw=8

" Search settings
set ignorecase
set incsearch
set hlsearch

" Swap & Backup
set dir=$HOME/.vim/tmp

" Wildignore
set wildignore+=*.o,*.obj,.git,*.min.js,*.png,*.class,*.jpg,*.jar,*.pack,*.idx,*.gif,*.apk,*.dmg,*.exe,*.dll,*.bak,*.orig,*.swp,*.swo,*.pyc,*.swf,*.pdf,*.psd,*.zip,*.flv,*.ttf,*.gz,*.gpg,*.fla,node_modules,*.a,*.so,*.hi,dist/*

" Keybindings
set pastetoggle=<F11>
vnoremap < <gv
vnoremap > >gv
cmap w!! w !sudo tee % >/dev/null
com! Q q
com! W w
com! Wq wq
com! WQ wq
com! Bd bd
com! BD bd
nnoremap <C-p> :CommandT<CR>
nnoremap <F2> :CommandTBuffer<CR>

" Terminal cursor shape
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" Filetype Detection
au BufRead,BufNewFile *.cpp       set syntax=cpp11
au BufRead,BufNewFile *.h         set syntax=cpp11
au BufRead,BufNewFile *.mxml      set filetype=mxml
au BufRead,BufNewFile *.as        set filetype=actionscript
au BufRead,BufNewFile *.co        set filetype=coffee
au BufRead,BufNewFile *.cs        set filetype=coffee
au BufRead,BufNewFile *.go        set filetype=go
au BufRead,BufNewFile *.less      set filetype=less
au BufRead,BufNewFile *.php.tpl   set filetype=php
au BufRead,BufNewFile *.class     set filetype=php
au BufRead,BufNewFile *.lang      set filetype=lang
au BufRead,BufNewFile *.m         set filetype=objc

" Plugin Manager
call plug#begin()

Plug 'sheerun/vim-polyglot'
Plug 'davidhalter/jedi-vim'
Plug 'dense-analysis/ale'
Plug 'psf/black'
Plug 'klen/python-mode'

call plug#end()

" Colors
set bg=dark

" Author info for plugins
let g:snips_author = 'Ryan Munro'
let g:github_user = 'munro'
let g:github_token = $GITHUB_TOKEN

" Load local overrides
if filereadable($HOME . "/.vimrc.local")
    source $HOME/.vimrc.local
endif
