#!/usr/bin/env bash
if [[ $(git log -1 --format="%an") == $(git config --global user.name) ]]; then
    # echo 🍀🍀🍀🍀🍀🍀🍀🍀 Feeling Lucky 🍀🍀🍀🍀🍀🍀🍀🍀
    /usr/bin/time lucky_commit 133700
    # echo 🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀🍀
fi
